use Etrade2

-- adana ili satışları için aggregate fonkisyonlar
SELECT COUNT (*) AS COUNT , MIN(AMOUNT) AS MIN, MAX(AMOUNT) AS MAX, SUM(AMOUNT) AS SUM, AVG(AMOUNT) AS AVG 
FROM SALES
WHERE CITY = 'ADANA'

SELECT STRING_AGG(CAST(ITEMNAME AS VARCHAR(MAX)), ', ') 
FROM SALES

--bütün iller için satış istatistikleri
SELECT CITY,
MIN(TOTALPRICE) AS MIN, MAX(TOTALPRICE) AS MAX, SUM(TOTALPRICE) AS SUM, AVG(TOTALPRICE) AS AVG 
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC

--convert ile sanal sütun
SELECT CONVERT(DATE,DATE_) AS DATEDAY,*
FROM SALES WHERE CITY='ANKARA'
ORDER BY DATE_

--ŞEHİRLERDE GÜN BAZINDA SATIŞI
SELECT CITY,CONVERT(DATE,DATE_) AS DATEDAY,SUM(TOTALPRICE)
FROM SALES
GROUP BY CITY,CONVERT(DATE,DATE_) 
ORDER BY SUM(TOTALPRICE)

-- GÜN BAZLI MAĞAZA SATIŞI
SELECT CONVERT(DATE,DATE_) AS DATEDAY,CITY,SUM(TOTALPRICE)
FROM SALES WHERE CONVERT(DATE,DATE_)='2019-06-12'
GROUP BY CONVERT(DATE,DATE_), CITY
ORDER BY SUM(TOTALPRICE)

-- ADANA İLİNİN AYLARA GÖRE SATIŞ SAYILARI
SELECT 
    CITY,
    YEAR(DATE_) AS SaleYear,
    MONTH(DATE_) AS SaleMonth,
    SUM(Amount) AS TotalSales
FROM 
    SALES
WHERE 
    CITY='ADANA'
GROUP BY 
    CITY, 
    YEAR(DATE_), 
    MONTH(DATE_)
ORDER BY 
    CITY, 
    SaleYear, 
    SaleMonth;

-- KATEGORİLERFE GÖRE TOPLAM SATIŞ TUTARLARI
SELECT 
   CATEGORY1, SUM(TOTALPRICE)
FROM 
   SALES 
GROUP BY 
   CATEGORY1
ORDER BY 
   SUM(TOTALPRICE)

-- AYLIK BAZDA KAÇ FARKLI MÜŞTERİ MAĞAZALARA GELMİŞTİR
SELECT CITY, MONTH(DATE_), COUNT(DISTINCT CUSTOMERCODE) AS CUSTOMER
FROM SALES
GROUP BY CITY,MONTH(DATE_)

--ŞEHİRLERDE AYLIK BAZINDA KAÇ FİŞ KESİLMİŞ
SELECT CITY, MONTH(DATE_), COUNT(FICHENO) AS FICHE
FROM SALES
WHERE YEAR(DATE_) = '2019'
GROUP BY CITY,MONTH(DATE_)
ORDER BY CITY, MONTH(DATE_)

-- TOPLAM CİROSU 4000 ÜZERİNDE OLAN MAĞAZALAR, (AGGREGATE ŞART FONKSİYONLARIDNA WHERE KULLANILMAZ)
--(KOLONDA VERDİĞİMİZ HAVİNGDE KULLANILMAK ZORUNDA WHERE OLARAK DEĞİL)
SELECT CITY, SUM(TOTALPRICE)
FROM SALES
GROUP BY CITY
HAVING SUM(TOTALPRICE) > 4000
ORDER BY SUM(TOTALPRICE)

--BAZI İLLER ARASINDA TOPLAM CİROSU 40000 ALTINDA OLAN ŞEHİRLER
SELECT CITY, SUM(TOTALPRICE)
FROM SALES 
WHERE CITY IN ('ANKARA','ISTANBUL','İZMİR','AYDIN','HATAY')
GROUP BY CITY
HAVING SUM(TOTALPRICE) < 40000
ORDER BY CITY

-- EN SON SATIŞI YAPILAN 5 ÜRÜN 

SELECT TOP 5 I.ITEMNAME, S.ITEMCODE,MAX(DATE_)
FROM SALES S
JOIN ITEMS I ON S.ITEMCODE = I.ITEMCODE
GROUP BY S.ITEMCODE, I.ITEMNAME
ORDER BY MAX(DATE_) DESC

--SATIŞI EN FALZA OLAN ÜRÜN
SELECT TOP 1
I.ITEMNAME, S.ITEMCODE,COUNT(S.ITEMCODE) AS SALESCOUNT
FROM SALES S
JOIN ITEMS I ON S.ITEMCODE = I.ITEMCODE
GROUP BY I.ITEMNAME,S.ITEMCODE
ORDER BY SALESCOUNT DESC

--EN ÇOK SATIŞ YAPMIŞ 5 ŞEHİR VE SAYISI
SELECT TOP 5 S.CITY ,SUM(S.AMOUNT) AS TOTAL
FROM SALES S
GROUP BY CITY
ORDER BY TOTAL DESC

--HER ŞEHİRDE HER AY KAÇ FARKLI MÜŞTERİ ALIŞVERİŞ YAPTI
SELECT C.CITYNAME, MONTH(S.DATE_), COUNT(DISTINCT CU.ID)
FROM SALES S
JOIN CUSTOMERS CU ON S.CUSTOMERCODE=CU.ID
JOIN CITIES C ON S.CITY = C.CITYNAME
GROUP BY C.CITYNAME, MONTH(S.DATE_)
ORDER BY C.CITYNAME

--İKİ TABLO BİLREŞMESİ WHERE İLE (ESKİ STİL)
SELECT * FROM 
SALES ,CUSTOMERS
WHERE SALES.CUSTOMERCODE = CUSTOMERS.ID

--INNERJOIN ÖRNEK
SELECT C.* ,I.* 
FROM SALES S
INNER JOIN CUSTOMERS C ON S.CUSTOMERCODE=C.ID
INNER JOIN ITEMS I ON S.ITEMCODE = I.ITEMCODE

-- LEFTJOIN ÖRNEK
SELECT C.NAMESURNAME, S.ID
FROM CUSTOMERS C
LEFT JOIN SALES S ON C.ID = S.CUSTOMERCODE;

--RIGHTJOIN ÖRNEK
SELECT I.ITEMNAME, C.NAMESURNAME
FROM SALES S
RIGHT JOIN ITEMS I ON S.ITEMCODE = I.ITEMCODE
LEFT JOIN CUSTOMERS C ON S.CUSTOMERCODE = C.ID;

--FULL(OUTER) JOIN
SELECT C.NAMESURNAME, S.ID
FROM CUSTOMERS C
FULL OUTER JOIN SALES S ON C.ID = S.CUSTOMERCODE

--GERCEK HAYAT INNERJOIN
-- MÜŞTERİ ADI SOYADI, ALDIĞI ÜRÜN,İL,İLÇE ,SATIŞ ID, TARİH, TOPLAM TUTAR
SELECT  CU.NAMESURNAME, I.ITEMNAME, C.CITYNAME, D.TOWN, S.FICHENO, S.DATE_, S.TOTALPRICE, I.ITEMCODE, S.AMOUNT
FROM SALES S
INNER JOIN CUSTOMERS CU ON S.CUSTOMERCODE=CU.ID
INNER JOIN ITEMS I ON S.ITEMCODE = I.ITEMCODE
INNER JOIN CITIES C ON S.CITY = C.CITYNAME
INNER JOIN CITY_DISTRICT D ON C.CITYNAME= D.CITY

--ŞEHİRLERE GÖRE TOPLAM SATILAN ÜRÜN LİSTELEME 
SELECT C.CITYNAME, SUM(S.AMOUNT) SALES
FROM SALES S
INNER JOIN CITIES C ON C.CITYNAME=S.CITY
GROUP BY C.CITYNAME 
ORDER BY SALES DESC

--SUBQUERY 
-- SİPARİŞİ VERİP ŞEHRİ ANKARA OLAN KULLANICILAR

SELECT CU.NAMESURNAME
FROM CUSTOMERS CU
WHERE ID IN (
    SELECT CUSTOMERCODE
    FROM SALES
    WHERE CITY='Ankara'
  )

--HER MÜŞTERİNİN SATIN ALMA ORTAMALAMASI  
SELECT AVG(SALES_COUNT)
FROM (
    SELECT CUSTOMERCODE, COUNT(*) AS SALES_COUNT
    FROM SALES
    GROUP BY CUSTOMERCODE
) AS CUSTOMER_SALES;

-- SON 3 AYDA HANGİ ÜRÜNDEN KAÇ TANE SATILMIŞ
SELECT 
    I.ITEMNAME,
    SUM(AMOUNT) AS TOTAL_SALES,
    MONTH(S.DATE_)
FROM 
    ITEMS I
JOIN 
    (
        SELECT * 
        FROM SALES 
        WHERE DATE_ >= DATEADD(MONTH, -3, (SELECT MAX(DATE_) FROM SALES))
    ) AS S
    ON I.ITEMCODE = S.ITEMCODE
GROUP BY 
    I.ITEMNAME, MONTH(S.DATE_)
ORDER BY 
    MONTH(S.DATE_) ASC;

--HER ÜRÜNÜN EN DÜŞÜK SATIŞ FİYATI
SELECT I.ITEMNAME,
   (SELECT MIN(S.PRICE) 
    FROM SALES S
    WHERE I.ITEMCODE=S.ITEMCODE)
FROM ITEMS I





















