use Etrade2
--MUSTERİNİN BELİRLİ TARİH ARALIKLARINA GÖRE ALDIĞI ÜRÜM MİKTAR VE FİYATLARI, TARİH VERİLMEZSE HEPSİ
ALTER PROCEDURE GetCustomerSalesReport
@CustomerId INT,
@StartDate DATE = NULL,
@EndDate DATE = NULL
AS 

BEGIN
	IF @StartDate IS NULL
    SET @StartDate = (SELECT MIN(S.DATE_) FROM SALES S WHERE S.CUSTOMERCODE = @CustomerId);

    IF @EndDate IS NULL
    SET @EndDate = (SELECT MAX(S.DATE_) FROM SALES S WHERE S.CUSTOMERCODE = @CustomerId);

	SELECT C.NAMESURNAME ADSOYAD, I.ITEMNAME URUNADI, 
	        COUNT(S.ID) SATIS, SUM(S.AMOUNT) MIKTAR, SUM(S.TOTALPRICE) TOPLAMTUTAR
	FROM SALES S 
	INNER JOIN CUSTOMERS C ON C.ID = S.CUSTOMERCODE
	INNER JOIN ITEMS I ON I.ID=S.ITEMCODE
	WHERE S.DATE_ BETWEEN @StartDate AND @EndDate AND S.CUSTOMERCODE=@CustomerId
	GROUP BY C.NAMESURNAME,I.ITEMNAME
END

EXEC GetCustomerSalesReport
    @CustomerId = 268275; 
    --@StartDate = '', 
    --@EndDate = '';

-- TEMPDB OLUŞTURMA, SP'LERE MÜDAHALE EDEMEDİĞİMZDE
CREATE TABLE #RAPOR 
(ADSOYAD VARCHAR(50), URUNADI VARCHAR(200),	SATIS INT,	MIKTAR INT ,TOPLAMTUTAR FLOAT)

INSERT INTO #RAPOR
EXEC GetCustomerSalesReport
    @CustomerId = 268275; 
SELECT *FROM #RAPOR
